[package]
edition = "2021"
name = "name"
version = "0.1.0"
[dependencies]
clap = { version = "3.2.16", features = ["derive"] }
figment = { version = "0.10.6", features = ["toml", "env"] }
serde = { version = "1.0.141", features = ["derive"] }
